server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kirilNikolov97/spring-cloud-config-store-rent
          search-paths:
            - 'service-config/*service'
